# Generated by Django 5.2.11 on 2026-02-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="employee_type",
            field=models.CharField(
                choices=[("employee", "Сотрудник"), ("manager", "Менеджер")],
                default="employee",
                max_length=20,
                verbose_name="Тип сотрудника",
            ),
        ),
    ]
