# Generated by Django 5.2.11 on 2026-02-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0002_employee_employee_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="full_name",
            field=models.CharField(max_length=255, verbose_name="ФИО"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="position",
            field=models.CharField(max_length=255, verbose_name="Должность"),
        ),
    ]
