# Generated by Django 5.2.11 on 2026-02-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
